name: DevOps Learning Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: Varsha0302/app-config-demo
          path: config

      - name: List repository files
        run: ls -la

      - name: Print message
        run: echo "Pipeline executed successfully"

      - name: Use secret
        run: echo ${{ secrets.MY_SECRET }}
